import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "sideMail Project - Automatically generated by sideMail",
  description: "A Next.js project automatically generated by sideMail",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

